# config/application.yml
# modify following values appropriately
defaults: &defaults
  secret_token: '9c212a84329b7e001954ab4911b65371f451273ae642d4c40ec0fb9dbaa9b7f3a5b7f4f8a8ed09c7f6bee63515aad28f8b0b8d64024ec1130a7252380fe760c0'
  twitter:
    key: 'development_key'
    secret: 'development_secret'
  allow_users: '18569149,282933021,213973213'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  twitter:
    key: <%= ENV['TWITTER_KEY'] %>
    secret: <%= ENV['TWITTER_SECRET'] %>
  allow_users: <%= ENV['ALLOW_USERS'].inspect %>
